# Generated by Django 6.0.4 on 2026-04-25 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('growth_cycle_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('completed', 'Completed'), ('deactivated', 'Deactivated'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('current_stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='planted', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons_created', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='profiles.field')),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='seasons.croptype')),
            ],
        ),
        migrations.CreateModel(
            name='CropTypeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='crop_types/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('attachment_type', models.CharField(choices=[('reference_image', 'Reference Image'), ('growth_stage_guide', 'Growth Stage Guide'), ('disease_guide', 'Disease/Pest Guide'), ('variety_specs', 'Variety Specifications'), ('planting_guide', 'Planting Guide'), ('harvest_guide', 'Harvest Guide'), ('other', 'Other')], default='reference_image', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('growth_stage', models.CharField(blank=True, choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], help_text='If this attachment relates to a specific growth stage', max_length=50, null=True)),
                ('crop_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='seasons.croptype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crop_type_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], max_length=50)),
                ('notes', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_updates', to=settings.AUTH_USER_MODEL)),
                ('crop_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasons.cropseason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='field_updates/attachments/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('attachment_type', models.CharField(choices=[('crop_photo', 'Crop Photo'), ('issue_photo', 'Issue/Damage Photo'), ('measurement', 'Measurement Record'), ('weather_report', 'Weather Report'), ('pest_report', 'Pest/Disease Report'), ('other', 'Other')], default='crop_photo', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('field_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='seasons.fieldupdate')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'field_update_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cropseason',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('field',), name='one_active_season_per_field'),
        ),
        migrations.AddIndex(
            model_name='croptypeattachment',
            index=models.Index(fields=['crop_type', 'attachment_type'], name='crop_type_a_crop_ty_28a53e_idx'),
        ),
        migrations.AddIndex(
            model_name='croptypeattachment',
            index=models.Index(fields=['growth_stage'], name='crop_type_a_growth__f4672b_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldupdateattachment',
            index=models.Index(fields=['field_update', 'attachment_type'], name='field_updat_field_u_87bf68_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldupdateattachment',
            index=models.Index(fields=['created_at'], name='field_updat_created_570fe6_idx'),
        ),
    ]
